/**
 * Rasterizes the Material Icon Theme artwork the app needs and regenerates
 * `src/markdownFileIcons.generated.ts`.
 *
 * The native markdown renderer draws context chips from an image URI
 * (`Image.resolveAssetSource`), so mobile needs real bitmap assets rather than
 * the sprite the web client injects. Both surfaces read the same upstream
 * rules through `scripts/materialIcons.ts`, so a path resolves to the same
 * icon everywhere.
 *
 * macOS only: rasterizing uses `sips`. Run `vpr --filter @t3tools/mobile sync:file-icons`.
 */
import * as NodeChildProcess from "node:child_process";
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";
import * as NodeURL from "node:url";

import {
  buildMaterialIconData,
  MATERIAL_ICON_THEME_VERSION,
} from "../../../../../scripts/materialIcons.ts";

const scriptDirectory = NodePath.dirname(NodeURL.fileURLToPath(import.meta.url));
const moduleDirectory = NodePath.resolve(scriptDirectory, "..");
const outputDirectory = NodePath.join(moduleDirectory, "assets/file-icons");
const generatedSourcesPath = NodePath.join(moduleDirectory, "src/markdownFileIcons.generated.ts");
const generatedRulesPath = NodePath.join(moduleDirectory, "src/markdownFileIconRules.generated.ts");

/** 4x the 16pt size the chips and tree rows draw at, so the art stays crisp on every screen. */
const RASTER_SIZE = 64;

const data = buildMaterialIconData();

/** Symbol ids carry the `mi-` prefix the sprite needs; assets are keyed by the bare icon name. */
const iconName = (symbolId: string) => symbolId.replace(/^mi-/, "");

const referenced = new Set(
  [
    ...Object.values(data.byFileName),
    ...Object.values(data.byFileExtension),
    ...Object.values(data.byFolderName),
    data.defaultFileIcon,
    data.defaultFolderIcon,
  ].map(iconName),
);

NodeFS.rmSync(outputDirectory, { recursive: true, force: true });
NodeFS.mkdirSync(outputDirectory, { recursive: true });

for (const name of [...referenced].sort()) {
  const source = data.iconSvgById[name];
  if (source === undefined) throw new Error(`No upstream artwork for "${name}"`);
  const viewBox = /viewBox="([^"]+)"/.exec(source)?.[1] ?? "0 0 24 24";
  const body = source.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  const rootAttributes = /<svg([^>]*)>/.exec(source)?.[1] ?? "";
  const rootFill = /\bfill="([^"]*)"/.exec(rootAttributes)?.[1];

  const svgPath = NodePath.join(outputDirectory, `material_${name}.svg`);
  NodeFS.writeFileSync(
    svgPath,
    `<svg xmlns="http://www.w3.org/2000/svg" width="${RASTER_SIZE}" height="${RASTER_SIZE}" viewBox="${viewBox}"${rootFill === undefined ? "" : ` fill="${rootFill}"`}>${body}</svg>`,
  );
  NodeChildProcess.execFileSync(
    "sips",
    [
      "-s",
      "format",
      "png",
      svgPath,
      "--out",
      NodePath.join(outputDirectory, `material_${name}.png`),
    ],
    { stdio: "ignore" },
  );
  NodeFS.rmSync(svgPath);
}

function serializeRecord(record: Readonly<Record<string, string>>): string {
  const entries = Object.entries(record).sort(([left], [right]) => (left < right ? -1 : 1));
  return `{\n${entries
    .map(([key, symbolId]) => `  ${JSON.stringify(key)}: ${JSON.stringify(iconName(symbolId))},`)
    .join("\n")}\n}`;
}

const names = [...referenced].sort();
const banner = `// @generated by scripts/sync-material-file-icons.ts from material-icon-theme@${MATERIAL_ICON_THEME_VERSION}. Do not edit.
// Material Icon Theme is MIT licensed; see third-party-licenses.config.json.`;

// Assets live apart from the rules so resolving a path stays a pure lookup.
// Importing them pulls all 800-odd bitmaps into the bundle, which only the
// components that actually draw an icon should pay for.
NodeFS.writeFileSync(
  generatedSourcesPath,
  `${banner}
import type { ImageSourcePropType } from "react-native";

export const MARKDOWN_FILE_ICON_SOURCES = {
${names.map((name) => `  ${JSON.stringify(name)}: require("../assets/file-icons/material_${name}.png"),`).join("\n")}
} as const satisfies Readonly<Record<string, ImageSourcePropType>>;
`,
);

NodeFS.writeFileSync(
  generatedRulesPath,
  `${banner}
import type { MARKDOWN_FILE_ICON_SOURCES } from "./markdownFileIcons.generated";

type IconName = keyof typeof MARKDOWN_FILE_ICON_SOURCES;

/** Exact lowercase basename to icon name. */
export const MARKDOWN_FILE_ICON_BY_NAME: Readonly<Record<string, IconName>> = ${serializeRecord(data.byFileName)};

/** Extension without the leading dot ("ts", "spec.ts") to icon name. */
export const MARKDOWN_FILE_ICON_BY_EXTENSION: Readonly<Record<string, IconName>> = ${serializeRecord(data.byFileExtension)};

/** Exact lowercase directory name to icon name. */
export const MARKDOWN_FOLDER_ICON_BY_NAME: Readonly<Record<string, IconName>> = ${serializeRecord(data.byFolderName)};

export const MARKDOWN_DEFAULT_FILE_ICON: IconName = ${JSON.stringify(iconName(data.defaultFileIcon))};
export const MARKDOWN_DEFAULT_FOLDER_ICON: IconName = ${JSON.stringify(iconName(data.defaultFolderIcon))};
`,
);

console.log(
  `Rasterized ${names.length} icons into ${NodePath.relative(moduleDirectory, outputDirectory)}`,
);
