/**
 * Regenerates `apps/web/src/materialIcons.generated.ts` from the upstream
 * `material-icon-theme` package (MIT, material-extensions/vscode-material-icon-theme).
 *
 * Upstream ships both the artwork and the filename/extension/folder rules, so
 * the mapping is never hand-maintained here. Run `vpr icons:material` after
 * bumping the dependency; the mobile rasterizer reads the same data through
 * `buildMaterialIconData`.
 */
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";
import * as NodeURL from "node:url";

import { buildMaterialIconData, MATERIAL_ICON_THEME_VERSION } from "./materialIcons.ts";

const repositoryRoot = NodePath.resolve(
  NodePath.dirname(NodeURL.fileURLToPath(import.meta.url)),
  "..",
);
const outputPath = NodePath.join(repositoryRoot, "apps/web/src/materialIcons.generated.ts");

const data = buildMaterialIconData();

function serializeRecord(record: Readonly<Record<string, string>>): string {
  const entries = Object.entries(record).sort(([left], [right]) => (left < right ? -1 : 1));
  return `{\n${entries.map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`).join("\n")}\n}`;
}

const source = `// @generated by scripts/generate-material-icons.ts from material-icon-theme@${MATERIAL_ICON_THEME_VERSION}. Do not edit.
// Material Icon Theme is MIT licensed; see third-party-licenses.config.json.

/** One \`<symbol>\` per icon, injected into the document and each tree's shadow root. */
export const MATERIAL_ICON_SPRITE = ${JSON.stringify(data.sprite)};

/** Exact lowercase basename to symbol id. */
export const MATERIAL_ICON_BY_FILE_NAME: Readonly<Record<string, string>> = ${serializeRecord(data.byFileName)};

/** Extension without the leading dot ("ts", "spec.ts") to symbol id. */
export const MATERIAL_ICON_BY_FILE_EXTENSION: Readonly<Record<string, string>> = ${serializeRecord(data.byFileExtension)};

/** Exact lowercase directory name to symbol id. */
export const MATERIAL_ICON_BY_FOLDER_NAME: Readonly<Record<string, string>> = ${serializeRecord(data.byFolderName)};

export const MATERIAL_DEFAULT_FILE_ICON = ${JSON.stringify(data.defaultFileIcon)};
export const MATERIAL_DEFAULT_FOLDER_ICON = ${JSON.stringify(data.defaultFolderIcon)};
export const MATERIAL_ROOT_FOLDER_ICON = ${JSON.stringify(data.rootFolderIcon)};
`;

NodeFS.writeFileSync(outputPath, source);

const kilobytes = (value: number) => `${(value / 1024).toFixed(0)} KB`;
console.log(`Wrote ${NodePath.relative(repositoryRoot, outputPath)}`);
console.log(
  `  ${Object.keys(data.iconSvgById).length} icons, sprite ${kilobytes(data.sprite.length)}`,
);
console.log(
  `  rules: ${Object.keys(data.byFileName).length} names, ${Object.keys(data.byFileExtension).length} extensions, ${Object.keys(data.byFolderName).length} folders`,
);
